version: "3.7"

services:
  irc-server:
    image: wildflyext/ircd:23
    ## Uncomment the following to expose the server at localhost:6667, eg. if
    ## you want to interact with the bot using your own client.
    #ports:
    #  - 6667

  crikey-irc:
    build:
      context: .
    depends_on:
      - irc-server
    volumes:
      - ./src:/usr/src/crikey-irc/src
      - ./tests:/usr/src/crikey-irc/tests
      - ./Cargo.lock:/usr/src/crikey-irc/Cargo.lock
      - ./Cargo.toml:/usr/src/crikey-irc/Cargo.toml
    command:
      - cargo
      - run
      - irc-server:6667
